Runtime Error
Error: ./src/components/layout/header.tsx:7:1
Export Stage doesn't exist in target module
   5 | import Link from "next/link";
   6 | import { usePathname } from "next/navigation";
>  7 | import { Stage, Code, User, Mic, Menu, X } from "lucide-react";
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   8 |
   9 | import { cn } from "@/lib/utils";
  10 | import { Button } from "@/components/ui/button";

The export Stage was not found in module [project]/node_modules/lucide-react/dist/esm/lucide-react.js [app-client] (ecmascript) <exports>.
Did you mean to import Star?
All exports of the module are statically known (It doesn't have dynamic exports). So it's known statically that the requested export doesn't exist.

Call Stack
7

Show 5 ignore-listed frame(s)
<unknown>
error: ./src/components/layout/header.tsx (7:1)
<unknown> (Error:
./src/components/layout/header.tsx (7:1)

Fix error